# Name project
NAME	= so_long
 
CC		= cc
CFLAGS	= -Wall -Wextra -Werror

HEADER	= inc/so_long.h

# Colors
RESET	= \033[0m
RED		= \033[31m
BLUE	= \033[34m
YELLOW	= \033[33m
ORANGE	= \033[38;5;208m
GREEN	= \033[32m

# Files